exports.EVENT_GALACTUS_DROP = 'EVENT_GALACTUS_DROP';
exports.EVENT_COMPRESSION_START = 'EVENT_COMPRESSION_START';
exports.EVENT_COMPRESSION_DONE = 'EVENT_COMPRESSION_DONE';
exports.EVENT_COMPRESSION_FAILED = 'EVENT_COMPRESSION_FAILED';
exports.EVENT_UNSUPPORTED_GALACTUS_FILES = 'EVENT_UNSUPPORTED_GALACTUS_FILES';
exports.EVENT_SAVE_FILES = 'EVENT_SAVE_FILES';
exports.EVENT_SAVE_DONE = 'EVENT_SAVE_DONE';
exports.EVENT_FETCH_SETTINGS_START = 'EVENT_FETCH_SETTINGS_START';
exports.EVENT_FETCH_SETTINGS_DONE = 'EVENT_FETCH_SETTINGS_DONE';
exports.EVENT_FETCH_SETTINGS_FAILED = 'EVENT_FETCH_SETTINGS_FAILED';
exports.EVENT_UPDATE_CONFIG = 'EVENT_UPDATE_CONFIG';
exports.EVENT_HANDLE_CONFIG_CHANGED = 'EVENT_HANDLE_CONFIG_CHANGED';

exports.EVENT_ANALYTICS_APP_STARTED = 'EVENT_APP_STARTED';
exports.EVENT_ANALYTICS_MINIFIED = 'EVENT_MINIFIED';
