sudo: required
dist: trusty
language: c
matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
install:
  - nvm install 6
  - npm install
  - npm prune
script:
  - npm test
  - npm run dist
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"