sudo: required
dist: trusty
language: c
osx_image: xcode8
matrix:
  include:
    - os: osx
    - os: linux
addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
install:
  - nvm install 6
  - npm install
  - npm prune
script:
  - npm run dist
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"